services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      PORT: ${LEVANTAMIENTO_PORT:-3000}
      PG_HOST: ${DATABASE_HOST}
      PG_PORT: ${DATABASE_PORT}
      PG_USER: ${LEVANTAMIENTO_DB_USER}
      PG_PASSWORD: ${LEVANTAMIENTO_DB_PASSWORD}
      PG_DATABASE: ${LEVANTAMIENTO_DB_NAME}
      OVERPASS_URLS: ${OVERPASS_URLS:-https://overpass.kumi.systems/api/interpreter,https://overpass-api.de/api/interpreter,https://lz4.overpass-api.de/api/interpreter}
      OVERPASS_PING_TIMEOUT_MS: ${OVERPASS_PING_TIMEOUT_MS:-4000}
      OVERPASS_MIRROR_TTL_MS: ${OVERPASS_MIRROR_TTL_MS:-600000}
      OSM_OVERPASS_TIMEOUT: ${OSM_OVERPASS_TIMEOUT:-90}
      CACHE_TTL_SEC: ${CACHE_TTL_SEC:-600}
      SOCIALACCOUNT_OIDC_CERTS: ${SOCIALACCOUNT_OIDC_ID_TOKEN_ISSUER}/protocol/openid-connect/certs
      SOCIALACCOUNT_OIDC_ID_TOKEN_ISSUER: ${SOCIALACCOUNT_OIDC_ID_TOKEN_ISSUER}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE:true}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
    restart: unless-stopped
    volumes:
      - app_uploads:/usr/src/app/uploads
      - app_downloads:/usr/src/app/downloads

volumes:
  app_uploads:
  app_downloads:
