services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    network_mode: host
    restart: always
    volumes:
      - app_uploads:/usr/src/app/uploads
      - app_downloads:/usr/src/app/downloads

volumes:
  app_uploads:
  app_downloads:
