services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - PG_HOST=db
    depends_on:
      - db
    volumes:
      - app_uploads:/usr/src/app/uploads
      - app_downloads:/usr/src/app/downloads
    restart: always

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
      POSTGRES_DB: ${PG_DATABASE:-postgres}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  app_uploads:
  app_downloads:
